[changelog]
header = """
# Changelog

All notable changes to wayu will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}
"""
trim = true
footer = """
{% for release in releases %}\
[{{ release.version | trim_start_matches(pat="v") }}]: https://github.com/dvrd/wayu/releases/tag/{{ release.version }}
{% endfor %}
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  { pattern = '\(#([0-9]+)\)', replace = "([#${1}](https://github.com/dvrd/wayu/pull/${1}))" },
]
commit_parsers = [
  { message = "^feat",     group = "Added" },
  { message = "^fix",      group = "Fixed" },
  { message = "^refactor", group = "Changed" },
  { message = "^perf",     group = "Changed" },
  { message = "^docs",     group = "Documentation", skip = true },
  { message = "^test",     group = "Internal",      skip = true },
  { message = "^ci",       group = "Internal",      skip = true },
  { message = "^chore",    group = "Internal",      skip = true },
  { message = "^revert",   group = "Reverted" },
]
protect_breaking_commits = false
filter_commits = true
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
