version: '3'

vars:
  BIN_DIR: ./bin
  SRC_DIR: ./src
  TEST_DIR: ./tests
  BINARY_NAME: wayu
  CONFIG_DIR: "{{.HOME}}/.config/wayu"

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
      - mkdir -p {{.BIN_DIR}}

  build:
    desc: Build the wayu CLI
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - odin build {{.SRC_DIR}} -out:{{.BIN_DIR}}/{{.BINARY_NAME}} -o:speed
    sources:
      - "{{.SRC_DIR}}/**/*.odin"
    generates:
      - "{{.BIN_DIR}}/{{.BINARY_NAME}}"

  debug:
    desc: Build with full debug information and logging
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - odin build {{.SRC_DIR}} -out:{{.BIN_DIR}}/{{.BINARY_NAME}}_debug -debug
    sources:
      - "{{.SRC_DIR}}/**/*.odin"
    generates:
      - "{{.BIN_DIR}}/{{.BINARY_NAME}}_debug"

  test:
    desc: Run all tests (unit, integration, and UI) with unified coverage report
    cmds:
      - ruby scripts/test-coverage.rb

  test:integration:
    desc: Run all standalone integration tests (Odin)
    deps: [build]
    cmds:
      - task test:path
      - task test:alias
      - task test:constants
      - task test:backup

  test:validation:
    desc: Run validation integration tests
    deps: [build]
    cmds:
      - ruby {{.TEST_DIR}}/integration/test_validation.rb

  test:errors:
    desc: Run error handling integration tests
    deps: [build]
    cmds:
      - ruby {{.TEST_DIR}}/integration/test_errors.rb

  test:completions:
    desc: Run completions integration tests
    deps: [build]
    cmds:
      - ruby {{.TEST_DIR}}/integration/test_completions.rb

  test:backup:
    desc: Run backup integration tests (Odin)
    deps: [build]
    cmds:
      - odin build {{.TEST_DIR}}/integration/test_backup_standalone.odin -file -out:{{.BIN_DIR}}/test_backup
      - "{{.BIN_DIR}}/test_backup"

  test:path:
    desc: Run PATH integration tests (Odin)
    deps: [build]
    cmds:
      - odin build {{.TEST_DIR}}/integration/test_path_standalone.odin -file -out:{{.BIN_DIR}}/test_path
      - "{{.BIN_DIR}}/test_path"

  test:alias:
    desc: Run alias integration tests (Odin)
    deps: [build]
    cmds:
      - odin build {{.TEST_DIR}}/integration/test_alias_standalone.odin -file -out:{{.BIN_DIR}}/test_alias
      - "{{.BIN_DIR}}/test_alias"

  test:constants:
    desc: Run constants integration tests (Odin)
    deps: [build]
    cmds:
      - odin build {{.TEST_DIR}}/integration/test_constants_standalone.odin -file -out:{{.BIN_DIR}}/test_constants
      - "{{.BIN_DIR}}/test_constants"

  test:plugin:
    desc: Run plugin integration tests (includes check/update Phase 2)
    deps: [build]
    cmds:
      - ruby {{.TEST_DIR}}/integration/test_plugin.rb

  test:plugin-update:
    desc: Run plugin check/update integration tests (Phase 2 - alias for test:plugin)
    deps: [build]
    cmds:
      - ruby {{.TEST_DIR}}/integration/test_plugin.rb

  test:init:
    desc: Run init and multi-shell integration tests
    deps: [build]
    cmds:
      - ruby {{.TEST_DIR}}/integration/test_init.rb

  test:dry-run:
    desc: Run dry-run mode integration tests
    deps: [build]
    cmds:
      - ruby {{.TEST_DIR}}/integration/test_dry_run.rb

  test:ui:
    desc: Run visual UI tests for manual inspection
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - odin run {{.TEST_DIR}}/ui/test_visual_alignment.odin -file -out:{{.BIN_DIR}}/test_visual
      - echo ""
      - odin run {{.TEST_DIR}}/ui/test_render_box.odin -file -out:{{.BIN_DIR}}/test_render

  test:components:
    desc: Run component rendering tests (unit tests only)
    cmds:
      - odin test {{.TEST_DIR}}/unit/test_components.odin -file

  test:components:snapshot:
    desc: Generate golden files for all components
    deps: [build]
    cmds:
      - mkdir -p tests/golden
      - "{{.BIN_DIR}}/{{.BINARY_NAME}} -c=box width=10 height=3 --snapshot"
      - "{{.BIN_DIR}}/{{.BINARY_NAME}} -c=box width=80 height=24 --snapshot"
      - "{{.BIN_DIR}}/{{.BINARY_NAME}} -c=list-item width=40 height=1 text='Sample item' --snapshot"
      - "{{.BIN_DIR}}/{{.BINARY_NAME}} -c=header width=60 height=3 title='Test Header' --snapshot"
      - "{{.BIN_DIR}}/{{.BINARY_NAME}} -c=footer width=80 height=3 shortcuts='q=quit' --snapshot"
      - "{{.BIN_DIR}}/{{.BINARY_NAME}} -c=scroll-indicator width=50 height=1 start=1 end=10 total=50 --snapshot"
      - "{{.BIN_DIR}}/{{.BINARY_NAME}} -c=empty-state width=60 height=10 message='No items found' --snapshot"
      - echo "✓ All golden files generated"

  test:all:
    desc: Run all tests (unit, integration, and UI) with unified report
    cmds:
      - task test

  run:
    desc: Build and run wayu
    deps: [build]
    cmds:
      - "{{.BIN_DIR}}/{{.BINARY_NAME}}"

  install:
    desc: Install wayu CLI to system
    deps: [build]
    cmds:
      - cp {{.BIN_DIR}}/{{.BINARY_NAME}} /usr/local/bin/{{.BINARY_NAME}}
      - chmod +x /usr/local/bin/{{.BINARY_NAME}}
      - ./{{.BIN_DIR}}/{{.BINARY_NAME}} init

  dev:
    desc: Development workflow (debug + run with args)
    deps: [debug]
    cmds:
      - "{{.BIN_DIR}}/{{.BINARY_NAME}}_debug"

  check:
    desc: Check Odin code
    cmds:
      - odin check {{.SRC_DIR}}

  all:
    desc: Clean, build, test, and install
    deps: [clean, build, test, install]

  help:
    desc: Show available tasks
    cmds:
      - task --list
